name: 'Main branch'

on:
  pull_request:
    branches: [main]
    types: [labeled]

jobs:

  test:
    name: "Testing project"
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: echo "Run test project"


  build:
    name: "Building project"
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'build')

    steps:
    - name: Test
      run: echo "Run build project"


  deploy:
    name: "Deploying project"
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy-nuget')

    steps:
    - name: Test
      run: echo "Run deploy project"
