name: 'Tests'

on:
  pull_request:
    branches: [main]
    types: [labeled]


jobs:

  test-project:
    name: "Testing project"
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy-nuget')

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.200'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build


  test2:
    name: "Second etst"
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: echo "Hello github"